remote_theme: vsanthanam/gh-index-theme

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            vs.os
tagline:          'open source projects by varun santhanam'
description:      'open source projects by varun santhanam'
url:              https://code.vsanthanam.com
baseurl:          ''
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Varun Santhanam'
  url:            https://www.vsanthanam.com

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
sidebar_home_link:  false
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
